### ISSUE TITLE
Installation Failed

### ISSUE THREAD

**Issue by sleeplessnight2** [craigk5n/webcalendar#112]
On the step where the Setup will create the Database it's crashed.

The Apache Error-Log said: Uncaught Error: Call to undefined function set_magic_quotes_runtime() in /pool/www/wawi/install/install_functions.php:458\nStack trace:\n#0 /pool/www/wawi/install/index.php(378): db_populate('tables-mysql.sq...', '1')\n#1 {main}\n  thrown in /pool/www/wawi/install/install_functions.php on line 458, referer: http://172.16.8.200/install/index.php?action=switch&page=3

set_magic_quotes_runtime() is not availaible in PHP7.0 anymore.

I using fresh install Debian 9, PHP7.0 and the Version 1.2.9 from your cal.

**Comment by FranzGotsis** [comment]
I would use the install/index.php file from the main trunk of the development. It currently solves this problem in a quite elegant way:

if( function_exists( 'set_magic_quotes_runtime' ) ) {
  $magic = @get_magic_quotes_runtime();
  @set_magic_quotes_runtime( 0 );
} else
  unset( $magic );

Basically it checks if the function exists, otherwise it ignores this option which is no longer supported in PHP 7 and also not necessary anymore.
The program WebCalendar turns "magic quotes" off before it reads passwords, to make sure the passwort is read in exactly the way it was written into the configuration file. It was necessary at a time when 8 Bit ASCII was the only format available. When you are using UTF (UTF8 or UTF16) you do not need that anyway as you can write almost any character you want in a regular way and I guess that was the reason it was deprecated.

In the source code (lines 105-134) all it does is to unset the magic quotes before reading from a file in binary mode. After reading from the file it is set back to its initial value. The function is reading from a textfile (the installation password) and therefore needs to make sure it is read in exactly the way it was written. PHP7 will always read the bytes the way they were written without interpreting some values as a magic quote, so this protection is no longer necessary.

kind regards
Franz
