### ISSUE TITLE
WebCalendar 1.2.9 / PHP greater than 7.0

### ISSUE THREAD

**Issue by ralf58** [craigk5n/webcalendar#127]
With PHP 7.0 WebCalendar 1.2.9 works fine. Because patches for PHP 7.0 will stop in some days, I tested WebCalendar with PHP 7.1 and it don't works fine:
The public access is possible, but by signing in, I got an empty side or the hhtp-error "500".
Any idea?

PROGRAM_NAME:
WebCalendar v1.2.9 (24 Aug 2017)

SERVER_SOFTWARE:
Apache/2.4.37 (Unix)

Web Browser:
Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:64.0) Gecko/20100101 Firefox/64.0

PHP Version:
7.0.33

Default Encoding:
iso-8859-1

db_type:
mysqli

**Comment by craigk5n** [comment]
I"m not getting any errors using PHP 7.1.  You can try out the PHP 7.1 using the docker setup here (uses SQLite instead of MySQL):

https://github.com/craigk5n/webcalendar-docker

What does the web server log say?  (This would be /var/log/apache2/error.log on Ubuntu, but may be different for your setup.)

I also use PHP 7.2 on my dev setup on Ubuntu 18 with MySQL with no issues.

**Comment by ralf58** [comment]
I got this php-information per "php.ini":

Warning: Illegal string offset 'name' in /mnt/web018/c1/96/5705096/htdocs/WebCalendar-1.2.9/includes/menu/index.php on line 238 Warning: Illegal string offset 'url' in /mnt/web018/c1/96/5705096/htdocs/WebCalendar-1.2.9/includes/menu/index.php on line 239 Fatal error: Uncaught Error: [] operator not supported for strings in /mnt/web018/c1/96/5705096/htdocs/WebCalendar-1.2.9/includes/menu/index.php:240 Stack trace: #0 /mnt/web018/c1/96/5705096/htdocs/WebCalendar-1.2.9/includes/init.php(154): include_once() #1 
/mnt/web018/c1/96/5705096/htdocs/WebCalendar-1.2.9/month.php(96): print_header(Array, '\n

I replaced my includes/menu/index.php with code from https://github.com/craigk5n/webcalendar/blob/master/includes/menu/index.php and now it's running fine using PHP 7.1 or 7.2.
