### ISSUE TITLE
Calendar Timezone

### ISSUE THREAD

**Issue by lawresolve** [craigk5n/webcalendar#136]
Hi,

Out of the blue, all our events in our calendar began displaying the incorrect time. For example, events that were entered at 10:00 AM are now displaying as beginning at 4:00 PM. 

I went into the system settings and both the timezone and system timezone are set to America/Los Angeles as they should be. However, next to that it lists GMT offset as 0.

I attempted to change the time zone to another country in the hopes of resetting the time but the times did not change at all and the GMT offset remained at 0.

How can the events be changed back to their original times ? There are far to many to go through and edit each event individually.

Thank you!

**Comment by craigk5n** [comment]
If I had to guess, something changed on your server (a PHP upgrade or config change?) that caused the issue.  If you are seeing that your offset from GMT is zero, that is the source of the problem.   If the offset to GMT is zero, you are seeing GMT times for your events instead of Pacific time.

**Comment by lawresolve** [comment]
Hi, thank you for your response. Yes, the GMT appears to be set to zero, how can the GMT be changed ?
Thank you!

**Comment by craigk5n** [comment]
You'll need to tell your PHP installation which timezone, which requires updating the php.ini file.  See more from [Google](https://www.google.com/search?q=setting+the+timezone+for+PHP&oq=setting+the+timezone+for+PHP&aqs=chrome..69i57j0l4.7446j0j4&sourceid=chrome&ie=UTF-8).

**Comment by liderbug** [comment]
I recently upgraded to 1.3.0  and I have a like problem.  I'm in MST (Denver), server is in LA.  To get my times to display right I have to set all timezones to New York (GMT-4).  Otherwise all the times are 2 hrs early - event at 10 AM displays 8 AM.  I've set date_default_timezone_set ( "America/Denver"); in index.php and inc../init.php.
webcal_timezones has 2 entries: no TZ description and America/Denver.  Before the upgrade 10am was 10am.
Thanks
