### ISSUE TITLE
WebCalendar v1.3.0: Load "normalize.css" from web server serving WebCalendar instead of CDN

### ISSUE THREAD

**Issue by codifex** [craigk5n/webcalendar#141]
WebCalendar v1.3.0 loads "normalize.css" from a CDN:

`<link href="//cdnjs.cloudflare.com/ajax/libs/normalize/6.0.0/normalize.css" rel="stylesheet">`

This line is written to the HTML output on line 131 of "init.php".

Loading "normalize.css" from the CDN poses a problem if access to external servers is blocked (e.g., in an intranet or with certain content origin rules in action).

It would therefore be preferable to include "normalize.css" in the release package so it gets installed and loaded on/from the web server that serves WebCalendar.

**Comment by FranzGotsis** [comment]
You could do your proposed changes in your own account and create a pull request, which is essentially a request to merge your changes with the main branch. Craig usually includes that if there is no conflict.

I think that this is good change. The side-effect is that you cannot automatically profit from improvements of the css. In my view this problem is an acceptable side effect of the change.

Another (and more complicated) way would to define a setting variable and act upon that: If the configuration variable (setting) wants no external connections you use the file that came with the installation. If you allow external connections you use the remote file.

As I am not using version 1.3.0 I cannot do the change myself (at least not easily - I am still using a forked version of 1.2.9).

kind regards
Franz
