### ISSUE TITLE
Mass/Global Layers or other option?

### ISSUE THREAD

**Issue by liviboy** [craigk5n/webcalendar#202]
Hi there,

I want to use WebCalendar as a booking system. So around 30 users and they can choose to book a space by double clicking on the day and adding in the times.

I have set up a global view which is the default when anyone logs in.

However, they cannot see any other user's booking unless they add them to a layer.

Is it possible to do this en-masse so that whenever a user is created they automatically see everyone else's bookings/events? Or do I need to set it up manually every time I add a user (and that would include going in and adding the new user to every existing account)?

Thank you so much in advance!

**Comment by tberry2112** [comment]
I'm trying to enable a very similar functionality. 

> Is it possible to do this en-masse so that whenever a user is created they automatically see everyone else's bookings/events? Or do I need to set it up manually every time I add a user (and that would include going in and adding the new user to every existing account)?

**Comment by craigk5n** [comment]
Have you tried using a custom view the includes "All" rather than selected users?  You can also change the default view to one of the custom views.
Note that if don't already have any custom views, there was a bug preventing you from adding/using views.  The latest code in the master branch fixes this.

See screenshot:
![image](https://user-images.githubusercontent.com/5342249/105549026-6dcb7200-5cce-11eb-9219-33aec10a3a94.png)
