### ISSUE TITLE
Installation worked but it is not possible to open Events Details

### ISSUE THREAD

**Issue by jessidevil** [craigk5n/webcalendar#392]
### Discussed in https://github.com/craigk5n/webcalendar/discussions/390

<div type='discussions-op-text'>

<sup>Originally posted by **jessidevil** August 10, 2023</sup>
I have installed the webcalendar-master on my Server:

|SYSTEM INFORMATION&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;| |
|---|---|
|  OS type and version |     Ubuntu Linux 22.04.3     |
|  Kernel and CPU  |  Linux 5.15.0-78-generic auf x86_64  |
|  Webmin-Version  |  2.101  |
|  Usermin-Version  |  2.001  |
|  Virtualmin Version  |  7.7.  |
|  Authentic theme version  |  21.04  |
|  Apache Version  |  2.4.52  |
|  PHP Version  |  8.1.2  |
|  MariaDB Version  |  10.6.12  |

All looks good, you can see Events in the Overview Month, Week, Daily,... but if you click it you will only get a Error 500 from the Server. Any Ideas?

Thanks in Advance :)

</div>

**Comment by AxelDuerrbaum** [comment]
Changing the order of the "require_once" in line 18 to 21 in view_edit.php solves the problem:

require_once 'includes/classes/Doc.php';
require_once 'includes/classes/DocList.php';
require_once 'includes/classes/CommentList.php';
require_once 'includes/classes/AttachmentList.php';

Because AttachementList.php extends DocList !

**Comment by automotorcanarias** [comment]
https://github.com/craigk5n/webcalendar/issues/388

**Comment by craigk5n** [comment]
It should be fixed in the latest code in the master branch.
