### ISSUE TITLE
Failing to install 1.9.1 (invalid form request)

### ISSUE THREAD

**Issue by lindemann06** [craigk5n/webcalendar#434]
I've installed 1.9.1 as an upgrade to 1.3, but even though the installation process went perfectly, launching the calendar results in blank pages, with no login form required. Any ideas would be gratefully tried.

Thanks!

Rob Wood

### Discussed in https://github.com/craigk5n/webcalendar/discussions/301

<div type='discussions-op-text'>

<sup>Originally posted by **salocinlofos** July 14, 2022</sup>
Hi!

After using WebCalendar for many years, I'm trying to install a fresh 1.9.1.
After copying the files to my host, I point my browser to the WebCalendar directory and get the very first page: "Installation step 1".
The session counter works, all PHP settings are "on" with exception of safe mode (which is "off")  and I assign a password to the settings file.
Clicking "set password" brings me to:

> WebCalendar Error
>
> Fataler Fehler: Invalid form request

I don't have a clue to proceed from here.

Thanks for any help, it must be something basic/weird, since I don't find any google hits on this subject...</div>

**Comment by craigk5n** [comment]
That installer has had some bugs since 1.9.0.  I'm working on a fix.  In the mean time, you can apply the db changes manually.  Look at the install/sql/upgrade-mysql.sql file to see what changes need to made to your database.  Once you've made those, you may also need to update the version stored in the database as well using (assuming you are on version "v1.9.1" rather than the most recent):

update webcal_config set val_value = 'v1.9.1' where cal_setting = 'WEBCAL_PROGRAM_VERSION';

**Comment by craigk5n** [comment]
Did that resolve the problem?

**Comment by craigk5n** [comment]
Any luck getting it working?

**Comment by craigk5n** [comment]
If you still need help, just re-open this issue.
