### ISSUE TITLE
Event popups are "blacked out" 

### ISSUE THREAD

**Issue by Tharrington86** [craigk5n/webcalendar#441]
When pop ups are enabled they appear as a blacked out box. 
![image](https://github.com/craigk5n/webcalendar/assets/75510358/2f212455-96a2-426f-ad0f-0044688db536)

I thought that this may be related to deploying to calendar in an iframe, but I navigated to the calendar using the URL and the issue remained. 

Version 1.9.10

**Comment by craigk5n** [comment]
It looks like the colors for your event popups are all set to black.  This can be set in System Settings (under "Colors") and overridden on a per-user basis in each users Preferences settings.  If you "View Source" on the page, check to see if the event text is actually present.  You should see a series of event info listings inside a <dl> tag near the bottom of the source that look something like the following:

```
<dl id="eventinfo-pop835324-20" class="popup">
  <dt>Event description here...</dt>
  <dt>Time:</dt>
  <dd>1:00pm - 11:59pm</dd>
  <dt>Description:</dt>
  <dd>Event description here....</dd>
</dl>

```
If that's there, then popup text is present (which I suspect it is due to the size of the black box).

**Comment by Tharrington86** [comment]
Doh! Someone was playing where they shouldn't've have been! Thank you.
