### ISSUE TITLE
"Invalid referring URL" error when adding an appointment with Safari 10.1.2

### ISSUE THREAD

**Issue by cesare2017** [craigk5n/webcalendar#5]
I am using Safari 10.1.2 with macOS Sierra 10.12.6. We use PHP 5.6

Its not possible to add an appointment, I get the following error **"Invalid referring URL"**.

We are having the same problem with the latest version 1.3.0 as well as with 1.2.7. Upgrading to 1.3.0 didn't solve the problem...As a workaround we used a different browser (Chrome, Firefox latest versions are OK) just for that...

**I now fixed it temporarily with Eribertos suggestion:** https://sourceforge.net/p/webcalendar/discussion/11588/thread/cf59cd8c/

This fix **doesn't work** for Safari latest version: https://sourceforge.net/p/webcalendar/bugs/2607/

Maybe you could integrate a (proper) fix for the next version.

**Comment by craigk5n** [comment]
The latest code in master introduces a way to disable the HTTP_REFERER check by adding a new settings to includes/settings.php.  If you want to do this with 1.2.7, here's the commit you would need to add to includes/functions.php:

https://github.com/craigk5n/webcalendar/commit/0e29c4508ed4a1fc57ac8f6d833bb8402d6129be

FYI, I found that running webcalendar inside docker also presents this problem since the SERVER_URL that WebCalendar sees is a different IP given by docker rather than the IP seen in your browser.

**Comment by cesare2017** [comment]
thanks a lot for your hint. didn't know that this functionality existed.

**Comment by cesare2017** [comment]
@craigk5n: the description here is wrong: https://github.com/craigk5n/webcalendar/commit/0e29c4508ed4a1fc57ac8f6d833bb8402d6129be

> ...Add 'disable_referer_check: **false**' to includes/settings.php to
turn off this check if you are getting this problem.

it should be:

> ...Add 'disable_referer_check: **true**' to includes/settings.php to
turn off this check if you are getting this problem.
