### ISSUE TITLE
Invalid referring URL after switching from http to https

### ISSUE THREAD

**Issue by liderbug** [craigk5n/webcalendar#69]
Running V1.2.7 - life was good and no problems.  Added a Cert and switched over to httpS -  Calendar comes up but when I try to add an event and "Save" I get "Invalid referring URL".  
In includes/functions.php I commented out "die_miserable_death" and it seems to be working again - I hope it's working - but something else may have broken.
It fails because "$_SERVER['HTTP_REFERER']" is empty.

What is the proper fix?  Thanks

**Comment by mickh1234** [comment]
I also had "Invalid referring URL" on all pages that I tried to open (using https).
I solved the problem by commenting out "die_miserable_death" in includes/functions.php (around line 6411) and was then able to open Settings/System Settings in my instance of WebCalendar and changing the Server Url setting to the correct path for my installation (Do not forget the trailing slash). I then went back and uncommented the incudes/functions file and all is working ok. I had previously tried changing the value in the database manually but this did not work because the value needs to be changed in the Settings/System Settings page.
Hope this helps.

**Comment by lizzyfin** [comment]
Thanks for taking time to comment, mickh1234! Saved me time!!

**Comment by Danlouis9701** [comment]
I had the same problem with https and I solved the problem, this helps, thank you very much

**Comment by maulepilot** [comment]
No need to comment out the php code. Go to the database webcal_config table and edit the SERVER_URL column. My site is https but the installation defaults to http.

**Comment by marcnyc2001** [comment]
> I also had "Invalid referring URL" on all pages that I tried to open (using https). I solved the problem by commenting out "die_miserable_death" in includes/functions.php (around line 6411) and was then able to open Settings/System Settings in my instance of WebCalendar and changing the Server Url setting to the correct path for my installation (Do not forget the trailing slash). I then went back and uncommented the incudes/functions file and all is working ok. I had previously tried changing the value in the database manually but this did not work because the value needs to be changed in the Settings/System Settings page. Hope this helps.

Thanks for posting this because I had the same issue and changing it manually in phpmyadmin had not worked, but doing it your way did work, so THANKS for taking the time to post!
