### ISSUE TITLE
Advanced Search does not work

### ISSUE THREAD

**Issue by Siderealist** [craigk5n/webcalendar#72]
Current build out of github, Apache 2.4.27, PHP 7.1.9

Normal searches out of the search box work fine, but all advanced searches only search the logged-in user (even if you select other users), and return this error message:

Warning: addslashes() expects parameter 1 to be string, array given in /usr/local/apache2/htdocs/.../calendar/includes/formvars.php on line 112

**Comment by FranzGotsis** [comment]
I tried to reproduce the error but with my installation, but I could reproduce the problem. 
My code is based on 1.2.9, running on MySQL or MariaDB (2 installations). The changes I did can be found at:
https://github.com/craigk5n/webcalendar/pull/77

I checked whether the problem might have gone away because of the changes I made. I did change code in /includes/formvars.php, although not in the function getPostValue where addslashes is called, so I guess the problem can be produced only if the function getPostValue ( $name ) is called with an argument (variable name) that does not appear in the post code. This is kind of strange as the variable is generated by the form and should be there in any case.

the call is: addslashes ( $_POST[$name] )
The call will fail if $name is not in the POST variable set generated by the form page.
In the file <installation path>/search.php in the generated html-code you find that the search string is named "keywords". And exactly that name is searched in the file <installation path>/search_handler.php.

Just one last thought: This might be due to a UTF-8 problem. I changed averything to UTF-8 by force in the database (via phpMyAdmin). That way a lot of problems disappear.

Looking at the PHP-Code the user you are using for the search might be lacking rights, which could explain the result. Even an administrator role user needs to set the proper rights for the search to work.

**Comment by craigk5n** [comment]
I've seen this problem come and go on my system as I've updated PHP versions... not sure what is causing it and I (unfortunately) cannot seem to reproduce it right now (using PHP 7.1.7 on Mac).

**Comment by pdivers** [comment]
My advanced search also does not work.
I'm using version 1.3.0 and get this error when I select users and press <select>:
"Program Error: No listid specified!"

The address bar contains:
https://www.***.com/webcalendar/usersel.php?form=searchformentry&listid=0&users=
