### ISSUE TITLE
Adding a new task creates an error message, because of a nunnumeric value - fixed

### ISSUE THREAD

**Issue by FranzGotsis** [craigk5n/webcalendar#81]
Adding a new task creates an error message, because of a nunnumeric value - fixed

Just a minor issue:
Creating a new task, if running on PHP 7.x leads to an error message that a nunumeric value is used. It boils down to line 453 in release 1.2.9. I fixed it and added a new pull-request.

old code:
// Avoid error for using undefined vars.
if ( ! isset ( $hour ) && $hour != 0 )
  $hour = -1;
else
if ( isset ( $hour ) && $hour >= 0 )
  $cal_time = ( $hour * 10000 ) + ( isset ( $minute ) ? $minute * 100 : 0 );

problem:
$minute can be set but it can be non numeric, so you have to check that as well

new code:
// Avoid error for using undefined vars.
if ( ! isset ( $hour ) && $hour != 0 )
  $hour = -1;
else
if ( isset ( $hour ) && $hour >= 0 )
{
	// FG: Make sure that $minute is set and numeric or set it to 0 to avoid am error message
	if (isset ( $minute ))
	{
		if (!is_numeric ($minute)) $minute = 0;
	}
	else $minute = 0;
	$cal_time = ( $hour * 10000 ) + ( $minute * 100 );
}

**Comment by bbannon** [comment]
I went looking for where $minute gets set in edit_entry.php.
I think there may be a problem in function time_selection ( ).
$time is always set since it's an incoming parameter.

Perhaps we should change 
- function time_selection ( $prefix, $time = '', $trigger = false ) {
+ function time_selection ( $prefix, $time = 0, $trigger = false ) {
  global $checked, $ENTRY_SLOTS, $selected, $TIME_FORMAT, $WORK_DAY_START_HOUR;

  $amsel = $pmsel = $ret = '';
  $trigger_str = ( $trigger ? 'onchange="' . $prefix . 'timechanged() ' : '' );

-  if ( ! isset ( $time ) && $time != 0 ) {
+  if ( $time === 0 ) {
    $hour = $WORK_DAY_START_HOUR;
    $minute = 0;
  } else {
    $hour = floor ( $time / 10000 );
    $minute = ( ( $time / 100 ) % 100 ) % 60;
  }

I'm not sure yet but, I think that may make your change unnecessary?

**Comment by craigk5n** [comment]
Fixed with commit (I think....):

729e69ada54fe37a8c9daf71fbf6777db926f31d
