### ISSUE TITLE
Creating new menu items (other users' calendars)

### ISSUE THREAD

**Issue by martinphone** [craigk5n/webcalendar#82]
My apologies if I've put this in the wrong place.

I'm looking at the custom menu part of menu_config.php and am just wanting to make a menu item containing direct links to the different users' calendars (rather than having to select from the select_user.php page).

I feel this must be pretty easily done in the $menuExtras section of menu_config.php but I don't know where to find out what I can actually put in here! Any help hugely appreciated.

I'm running 1.3.0.

**Comment by FranzGotsis** [comment]
You found the right place already: <root-installdirectory>\includes\menu\menu_config.php
You need to fill the array $menuExtras which is an array of arrays (2 dimensions).
There is a comment which explains what to do inside the file: (just copying form the file):
$menuExtras[2] =  array ( 'menu', 'My Example', '',
  array (
    array ( 'item', 'todo.png', 'New Todo', 'edit_entry.php?eType=task', ''),
    array ( 'item', 'week.png', 'View Week', 'week.php', ''),
    array ( 'divider' ),
    array ( 'submenu', 'manage_cal.png', 'External Links',
     array (
       array ( 'item', 'display.png', 'Google', 'http://www.google.com', '_blank'),
       array ( 'item', 'display.png', 'Craig&#39;s Site',
         'http://www.k5n.us/webcalendar.php', 'new')
     )
   )
 )
);
The handling of what happens if a menu item is selected, is specified in the entries referring to menuitems ("item"):
